---
- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yml"
    - "../vars/default.yml"
  when: sssd_package_name is not defined or sssd_service_name is not defined

- name: Instalamos sssd
  package: name={{ sssd_package_name }} state=present

- name: Instalamos autohome
  package: name={{ oddjob_package_name }} state=present

- name: Levantamos messagebus
  service: name=messagebus enabled=yes state=restarted

- name: comprobamos que se pueda resolver la ip del AD1 de itconic
  lineinfile: dest=/etc/hosts regexp='10.50.1.68.*tgs-w2pad1.tgs.local$' line="10.50.1.68	tgs-w2pad1.tgs.local" state=present
- name: comprobamos que se pueda resolver la ip del AD2 de itconic
  lineinfile: dest=/etc/hosts regexp='10.50.1.69.*tgs-w2pad2.tgs.local$' line="10.50.1.69	tgs-w2pad2.tgs.local" state=present

- name: comprobamos que se pueda resolver la ip del pimer ldap
  lineinfile: dest=/etc/hosts regexp='172.30.112.54.*vclldap1.yoigo.inet$' line="172.30.112.54	vclldap1.yoigo.inet" state=present
- name: comprobamos que se pueda resolver la ip del segundo ldap
  lineinfile: dest=/etc/hosts regexp='172.30.112.55.*vclldap2.yoigo.inet$' line="172.30.112.55	vclldap2.yoigo.inet" state=present

- name: comprobamos que se pueda resolver la ip del rhome
  lineinfile: dest=/etc/hosts regexp='10.50.1.83.*puppet.tgs.local.*puppet$' line="10.50.1.83	puppet.tgs.local puppet" state=present

- name: Paramos el demonio nscd
  service: name=nscd enabled=no state=stopped

- name: Levantamos el servicio autohome
  service: name=oddjobd enabled=yes state=restarted
