---
- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yml"
    - "../vars/default.yml"
  when: sssd_package_name is not defined or sssd_service_name is not defined

- name: Creamos directorio para almacenar los certificados
  file: path=/etc/sssd/certs state=directory mode=0755

- name: Obteniendo los certificados de confianza para vclldap1.yoigo.inet
  command: bash -c "echo -n | openssl s_client -connect vclldap1.yoigo.inet:1636 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > /etc/sssd/certs/vclldap1.yoigo.inet.pem"

- name: Obteniendo los certificados de confianza para vclldap2.yoigo.inet
  command: bash -c "echo -n | openssl s_client -connect vclldap2.yoigo.inet:1636 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > /etc/sssd/certs/vclldap2.yoigo.inet.pem"

- name: Obteniendo los certificados de confianza para ActiveDirectory
  copy: src=cert_ca.pem dest=/etc/sssd/certs/cert_ca.pem

- name: Calculamos el hash de los certificados
  command: cacertdir_rehash /etc/sssd/certs

- name: Copiamos la configuración de sssd
  template: src=sssd.conf.j2 dest=/etc/sssd/sssd.conf owner=root group=root mode=0600
  notify: restart sssd

- name: Arrancamos el servicio sssd
  service: name={{ sssd_service_name }} enabled=yes state=started

- name: Copiamos la configuración del cliente ldap
  template: src=ldap.conf.j2 dest=/etc/openldap/ldap.conf  owner=root group=root mode=0644
  
- name: Copiamos la configuración de nsswitch.conf
  template: src=nsswitch.conf.j2 dest=/etc/nsswitch.conf  owner=root group=root mode=0644

- name: authconfig PAM
  command: authconfig --enablesssd --enablesssdauth --enablemkhomedir --disableldap --disableldapauth --nostar --updateall

- name: Reiniciamos el servicio autohome
  service: name=oddjobd enabled=yes state=restarted
