---

# Cargarmos las variables de cada SO dependiendo de la familia que nos devuelva en el setup
- name: Icluimos variables
  include_vars: "{{ item }}"
  with_items:
    - "{{ ansible_os_family }}.yml"
    - "Common.yml"
  
# Copiamos los paquetes a la maquina dependiendo del gestor de paquetes
- name: Copy packages to system
  copy: src=dp9_{{ package_manager }}/ dest=/var/tmp/DP9_TMP
  register: copy
 
# Comprobamos si hay algun paquete de OB2 instalado en la maquina 
- name: Check if packets exist
  shell: "{{ package_local_search }}"
  register: pkg_installed
  ignore_errors: yes
  
# Recuperamos el cell que hay configurado si los paquetes estan instalados y si existe. Si no ignoramos el error   
- name: Register cell manager
  command: cat /etc/opt/omni/client/cell_server
  register: cell_server_local
  when: pkg_installed|success
  ignore_errors: yes

# Eliminamos los paquetes de data protector de la maquina si estaban instalados
- name: Remove all Data Protector Packages
  package: name={{item}} state=absent
  with_items: 
       # Listado de paquetes obtenido de la comprobación 
       - "{{ pkg_installed.stdout_lines }}"
  register: erase
  when: pkg_installed|success
  ignore_errors: yes
  
# Añadimos los paquetes de data protector en la version que lo hayamos copiado a la maquina y que hayamos puesto en las variables  
- name: Add Data Protector Packages
  command: "{{ package_local_install }} /var/tmp/DP9_TMP/{{ item }}"
  with_items: 
        - "{{ dp9_core }}"
        - "{{ dp9_da }}"
        - "{{ dp9_ma }}"
        
# Creamos el fichero con el cell al que tenemos que conectarnos siempre y cuando lo hayamos podido recuperar  
- name: Create cell manager file
  copy: content="{{ cell_server_local.stdout }}" dest=/etc/opt/omni/client/cell_server
  when: cell_server_local|success

# Si no hemos podido recuperar un cell local lo pasamos por variables  
- name: Create cell manager file
  copy: content="{{ cell_server }}" dest=/etc/opt/omni/client/cell_server
  when: cell_server_local|failed  
  
# Registramos la maquina dentro de data protector        
- name: Register machine in Data Protector not in local
  command: /opt/omni/bin/omnicc -update_host {{ ansible_fqdn }}
  when: pkg_installed|success
  
# Borramos los datos copiados  
- name: Delete copy files for Data Protector installation
  file: path=/var/tmp/DP9_TMP state=absent
  when: copy|success
  
